/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116549-g94165d1b79-20240808"
#endif /* AVUTIL_FFVERSION_H */
